name: central-bank-speech-alpha
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - transformers
    - torch
    - yfinance
    - fredapi
    - pandas
    - numpy
    - statsmodels
    - xgboost
    - scikit-learn
    - seaborn
    - matplotlib
    - datasets
    - git+https://github.com/eslazarev/purged-cross-validation.git
